### ISSUE TITLE
Implement improved whiteflag previous milestone checks

### ISSUE THREAD

**Issue by muXxer** [gohornet/hornet#1415]
- [x] Flag all messages containing a valid milestone payload (parents match, correct signature) as milestone in the metadata
- [x] Verify during whiteflag, that the last milestone is in the past cone by looking for a valid milestone with the same milestone ID.
- [x] Milestone should not confirm its own message after whiteflag
- [x] Enhance whiteflag test cases to cover the new last milestone ID checks
