### ISSUE TITLE
Change REST API for milestone payloads

### ISSUE THREAD

**Issue by muXxer** [gohornet/hornet#1418]
- [ ] Ensure iota.go/v3 hashes the milestone essence to generate milestone ID
- [ ] Return milestone payloads instead of messages
- [ ] Change `/milestones/{index}` to `/milestones/index/{index}`
- [ ] Add `/milestones/id/{milestoneId}`
