### ISSUE TITLE
Implement syncing with Milestone Chain

### ISSUE THREAD

**Issue by muXxer** [gohornet/hornet#1419]
- [ ] Add new index for "solidified" milestone payload chain
- [ ] Sync Milestone payload chain starting with latest milestone via gossip
- [ ] Change STING protocol to request milestone IDs instead of indexes
- [ ] Start WarpSync after Milestone Chain was verified
