### ISSUE TITLE
Change database layout for Milestone Payloads

### ISSUE THREAD

**Issue by muXxer** [gohornet/hornet#1421]
- [ ] Remove Index to MessageID Lookup
- [ ] Add Index to MilestoneID Lookup
- [ ] Add MilestoneID to MilestonePayload Lookup
